name: Deploy to GitHub Pages

# Only run this workflow on pushes to main that change index.html
on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      #  Check out your repository
      - name: Checkout repo
        uses: actions/checkout@v4

      #  Deploy to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The folder to publish; if you’re just publishing index.html at root:
          publish_dir: ./
          # Ensure we push to gh-pages branch
          publish_branch: gh-pages
